"""
Pyrogram Script Generator Bot
=============================
A Telegram bot (built with Pyrogram) that generates ready-to-use
Pyrogram bot script templates on demand, and lets the user download
them as a .py file. Deployable to Heroku.

Commands:
    /start      - welcome message + menu
    /generate   - pick a template and get a generated script
    /help       - usage info

Environment variables required (set these in Heroku Config Vars):
    API_ID      - your Telegram API ID        (https://my.telegram.org)
    API_HASH    - your Telegram API HASH
    BOT_TOKEN   - your bot token from @BotFather
"""

import os
import io
import logging
from datetime import datetime

from pyrogram import Client, filters
from pyrogram.types import (
    InlineKeyboardMarkup,
    InlineKeyboardButton,
    CallbackQuery,
    Message,
)

# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------

API_ID = int(os.environ.get("API_ID", "0"))
API_HASH = os.environ.get("API_HASH", "")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

if not (API_ID and API_HASH and BOT_TOKEN):
    raise SystemExit(
        "Missing API_ID / API_HASH / BOT_TOKEN. "
        "Set them as environment variables (Heroku Config Vars)."
    )

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
log = logging.getLogger("generator-bot")

app = Client(
    "pyrogram_generator_bot",
    api_id=API_ID,
    api_hash=API_HASH,
    bot_token=BOT_TOKEN,
)

# --------------------------------------------------------------------------
# Templates
# A dict of template_id -> (title, description, generator_function)
# Each generator function returns the full source code of a standalone
# Pyrogram script as a string.
# --------------------------------------------------------------------------


def tpl_echo() -> str:
    return '''"""
Echo Bot — generated by Pyrogram Script Generator Bot
Replies to every text message with the same text.
"""

import os
from pyrogram import Client, filters

API_ID = int(os.environ.get("API_ID", "0"))
API_HASH = os.environ.get("API_HASH", "")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

app = Client("echo_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)


@app.on_message(filters.command("start"))
async def start(client, message):
    await message.reply_text("Hi! Send me any text and I will echo it back.")


@app.on_message(filters.text & ~filters.command("start"))
async def echo(client, message):
    await message.reply_text(message.text)


if __name__ == "__main__":
    app.run()
'''


def tpl_welcome() -> str:
    return '''"""
Group Welcome Bot — generated by Pyrogram Script Generator Bot
Greets new members when they join a group/supergroup.
"""

import os
from pyrogram import Client, filters
from pyrogram.types import ChatMemberUpdated

API_ID = int(os.environ.get("API_ID", "0"))
API_HASH = os.environ.get("API_HASH", "")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

app = Client("welcome_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)


@app.on_message(filters.new_chat_members)
async def welcome(client, message):
    for member in message.new_chat_members:
        name = member.first_name or "there"
        await message.reply_text(
            f"Welcome, {name}! Please read the group rules pinned above."
        )


@app.on_message(filters.command("start"))
async def start(client, message):
    await message.reply_text("Welcome bot is running. Add me to a group as admin.")


if __name__ == "__main__":
    app.run()
'''


def tpl_admin() -> str:
    return '''"""
Admin/Moderation Bot — generated by Pyrogram Script Generator Bot
Basic group moderation: /ban, /unban, /mute, /unmute, /kick.
Bot must be a group admin with the relevant permissions.
"""

import os
from pyrogram import Client, filters
from pyrogram.types import ChatPermissions

API_ID = int(os.environ.get("API_ID", "0"))
API_HASH = os.environ.get("API_HASH", "")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

app = Client("admin_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)


def admin_only(func):
    async def wrapper(client, message):
        member = await client.get_chat_member(message.chat.id, message.from_user.id)
        if member.status not in ("administrator", "creator"):
            await message.reply_text("You must be an admin to use this command.")
            return
        await func(client, message)
    return wrapper


@app.on_message(filters.command("ban") & filters.group)
@admin_only
async def ban(client, message):
    if not message.reply_to_message:
        await message.reply_text("Reply to a user's message with /ban.")
        return
    target = message.reply_to_message.from_user.id
    await client.ban_chat_member(message.chat.id, target)
    await message.reply_text("User banned.")


@app.on_message(filters.command("unban") & filters.group)
@admin_only
async def unban(client, message):
    if not message.reply_to_message:
        await message.reply_text("Reply to a user's message with /unban.")
        return
    target = message.reply_to_message.from_user.id
    await client.unban_chat_member(message.chat.id, target)
    await message.reply_text("User unbanned.")


@app.on_message(filters.command("mute") & filters.group)
@admin_only
async def mute(client, message):
    if not message.reply_to_message:
        await message.reply_text("Reply to a user's message with /mute.")
        return
    target = message.reply_to_message.from_user.id
    await client.restrict_chat_member(
        message.chat.id, target, ChatPermissions()
    )
    await message.reply_text("User muted.")


@app.on_message(filters.command("unmute") & filters.group)
@admin_only
async def unmute(client, message):
    if not message.reply_to_message:
        await message.reply_text("Reply to a user's message with /unmute.")
        return
    target = message.reply_to_message.from_user.id
    await client.restrict_chat_member(
        message.chat.id,
        target,
        ChatPermissions(
            can_send_messages=True,
            can_send_media_messages=True,
            can_send_other_messages=True,
        ),
    )
    await message.reply_text("User unmuted.")


@app.on_message(filters.command("kick") & filters.group)
@admin_only
async def kick(client, message):
    if not message.reply_to_message:
        await message.reply_text("Reply to a user's message with /kick.")
        return
    target = message.reply_to_message.from_user.id
    await client.ban_chat_member(message.chat.id, target)
    await client.unban_chat_member(message.chat.id, target)
    await message.reply_text("User kicked.")


if __name__ == "__main__":
    app.run()
'''


def tpl_inline() -> str:
    return '''"""
Inline Query Bot — generated by Pyrogram Script Generator Bot
Responds to inline queries (typed as @yourbot query in any chat).
"""

import os
from pyrogram import Client, filters
from pyrogram.types import InlineQueryResultArticle, InputTextMessageContent

API_ID = int(os.environ.get("API_ID", "0"))
API_HASH = os.environ.get("API_HASH", "")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

app = Client("inline_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)


@app.on_inline_query()
async def answer(client, inline_query):
    query = inline_query.query or "Hello"
    results = [
        InlineQueryResultArticle(
            title="Send this text",
            input_message_content=InputTextMessageContent(query),
            description=f"Sends: {query}",
        )
    ]
    await inline_query.answer(results, cache_time=1)


@app.on_message(filters.command("start"))
async def start(client, message):
    await message.reply_text("Try me inline: type @your_bot_username and any text.")


if __name__ == "__main__":
    app.run()
'''


def tpl_callback() -> str:
    return '''"""
Inline Buttons / Callback Bot — generated by Pyrogram Script Generator Bot
Demonstrates inline keyboards and callback query handling.
"""

import os
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton

API_ID = int(os.environ.get("API_ID", "0"))
API_HASH = os.environ.get("API_HASH", "")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

app = Client("callback_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)


@app.on_message(filters.command("start"))
async def start(client, message):
    keyboard = InlineKeyboardMarkup(
        [
            [InlineKeyboardButton("Option A", callback_data="opt_a")],
            [InlineKeyboardButton("Option B", callback_data="opt_b")],
        ]
    )
    await message.reply_text("Choose an option:", reply_markup=keyboard)


@app.on_callback_query()
async def on_callback(client, callback_query):
    choice = callback_query.data
    await callback_query.answer(f"You picked {choice}", show_alert=False)
    await callback_query.message.edit_text(f"You selected: {choice}")


if __name__ == "__main__":
    app.run()
'''


TEMPLATES = {
    "echo": ("Echo Bot", "Replies with whatever text you send it.", tpl_echo),
    "welcome": ("Group Welcome Bot", "Greets new members on join.", tpl_welcome),
    "admin": ("Admin/Moderation Bot", "ban/unban/mute/unmute/kick commands.", tpl_admin),
    "inline": ("Inline Query Bot", "Handles @bot inline queries.", tpl_inline),
    "callback": ("Inline Buttons Bot", "Inline keyboards + callback queries.", tpl_callback),
}

# --------------------------------------------------------------------------
# Handlers
# --------------------------------------------------------------------------


def build_menu() -> InlineKeyboardMarkup:
    rows = []
    for key, (title, _desc, _fn) in TEMPLATES.items():
        rows.append([InlineKeyboardButton(title, callback_data=f"gen:{key}")])
    return InlineKeyboardMarkup(rows)


@app.on_message(filters.command("start"))
async def start_cmd(client: Client, message: Message):
    await message.reply_text(
        "**Pyrogram Script Generator Bot**\n\n"
        "I generate ready-to-run Pyrogram bot scripts.\n"
        "Use /generate to pick a template, or /help for more info.",
    )


@app.on_message(filters.command("help"))
async def help_cmd(client: Client, message: Message):
    lines = ["**Available templates:**\n"]
    for key, (title, desc, _fn) in TEMPLATES.items():
        lines.append(f"• `{key}` — {title}: {desc}")
    lines.append("\nRun /generate to choose one interactively.")
    await message.reply_text("\n".join(lines))


@app.on_message(filters.command("generate"))
async def generate_cmd(client: Client, message: Message):
    await message.reply_text(
        "Pick a template to generate:",
        reply_markup=build_menu(),
    )


@app.on_callback_query(filters.regex(r"^gen:(\w+)$"))
async def on_generate(client: Client, callback_query: CallbackQuery):
    key = callback_query.matches[0].group(1)
    template = TEMPLATES.get(key)
    if not template:
        await callback_query.answer("Unknown template.", show_alert=True)
        return

    title, _desc, generator_fn = template
    source_code = generator_fn()

    file_bytes = io.BytesIO(source_code.encode("utf-8"))
    file_bytes.name = f"{key}_bot.py"

    await callback_query.answer("Generating...")
    await callback_query.message.reply_document(
        document=file_bytes,
        caption=(
            f"**{title}**\n\n"
            f"Generated on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n"
            "Set `API_ID`, `API_HASH`, `BOT_TOKEN` as environment variables "
            "before running this script."
        ),
    )


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

if __name__ == "__main__":
    log.info("Starting Pyrogram Script Generator Bot...")
    app.run()
